using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SourceGenerator;

/// <summary>
/// Incremental source generator that unconditionally emits
/// <c>SourceGenLib.GeneratedHelper</c> into any project that references it as an analyzer.
/// Used by golden tests to verify that source-generated symbols are visible in the
/// metadata pipeline and can be iterated by templates.
/// </summary>
[Generator]
public sealed class HelloWorldGenerator : IIncrementalGenerator
{
    private const string GeneratedSource =
        """
        // <auto-generated/>
        namespace SourceGenLib
        {
            /// <summary>Helper class emitted by <c>HelloWorldGenerator</c>.</summary>
            public static class GeneratedHelper
            {
                /// <summary>Constant confirming the generator executed successfully.</summary>
                public const string GeneratorName = "HelloWorldGenerator";
            }
        }
        """;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("GeneratedHelper.g.cs", SourceText.From(GeneratedSource, Encoding.UTF8)));
    }
}
